#example: https://team.globalpay.com/teamGP/macroscope-appsec-properties#example
application_id = hrpos-react-native-view-shot
prod_branch = master
security_champion = eric.blumenstock@e-hps.com
out_of_scope = .readme, .github, example/Example
