// AutolinkedNativeModules.g.cs contents generated by "npx @react-native-community/cli autolink-windows"

using System.Collections.Generic;

// Namespaces from react-native-screens
using RNScreens;

// Namespaces from react-native-view-shot
using RNViewShot;

namespace Microsoft.ReactNative.Managed
{
    internal static class AutolinkedNativeModules
    {
        internal static void RegisterAutolinkedNativeModulePackages(IList<IReactPackageProvider> packageProviders)
        { 
            // IReactPackageProviders from react-native-screens
            packageProviders.Add(new RNScreens.ReactPackageProvider());
            // IReactPackageProviders from react-native-view-shot
            packageProviders.Add(new RNViewShot.ReactPackageProvider());
        }
    }
}
